# Etapa 1: Build Angular
FROM node:20-alpine as builder
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build -- --configuration production

# Etapa 2: Servir con NGINX
FROM nginx:stable-alpine
COPY --from=builder /app/dist/systembank/browser /usr/share/nginx/html
COPY ./nginx/load-balancer.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
